name 'my-delivery-truck'
maintainer 'Steve Brown'
maintainer_email 'stephenb583@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures my-delivery-truck'
long_description 'Installs/Configures my-delivery-truck'
version '0.3.3'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'fedora'
issues_url 'https://github.com/devoptimist/my-delivery-truck/issues'
source_url 'https://github.com/devoptimist/my-delivery-truck'
